### ISSUE TITLE
Build failure: could not find the <check.h> header

### ISSUE THREAD

**Issue by LoupVaillant** [Kleshni/Elligator-2#3]
Hi,

this repository fails to build on my system, I have no idea why. I run Ubuntu 18.04, and am building from master. Steps to reproduce:

    download gmp-6.2.0
    $ cd gmp-6.2.0
    $ ./configure
    $ make
    $ sudo make install

This apparently sucessfuly install GMP in `/usr/local/`, and pkg-config sees it:

    $ pkg-config gmp --cflags
    -I/usr/local/include
    $ pkg-config gmp --libs
    -L/usr/local/lib -lgmp

Building Elligator-2 however fails badly:

    $ cd ../Elligator-2
    $ cmake .
    $ make
    [ 14%] Building C object CMakeFiles/tests.dir/tests.c.o
    /home/loup/crypto/elligator-kleshni/tests.c:3:10: fatal error: check.h: No such file or directory

Any idea what might have gone wrong?

**Comment by tankf33der** [comment]
> Any idea what might have gone wrong?

You must install C test framework named [check](https://github.com/libcheck/check/).

```
$ cat CMakeLists.txt | grep link
target_link_libraries(library gmp)
target_link_libraries(tests gmp -lcheck)
```

**Comment by LoupVaillant** [comment]
OK, managed to do it, thanks. And apparently I can't read, those dependencies were listed in the Readme… Sorry for the invalid report.
